apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-minimal-backups
  labels:
    frequency: hourly
    full: "false"
spec:
  schedule: "15 */1 * * *"
  template:
    snapshotVolumes: false
    ttl: 960h0m0s
