name: check
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - uses: lablabs/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.20.3
      - name: lint
        run: |
          make lint
